### ISSUE TITLE
EPIC: Create user management, role management and application settings views and components

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall#86]
- [ ] User Management Views and Components 
  - [ ] User Profile Page
  - [ ] Password Reset
- [ ] Role/Circles Management Views and Components
- [ ] Application Settings Views and Components
  - [ ] Database settings and location
  - [ ] LDAP Settings authn and authz
  - [ ] GitHub / GitLab authn and authz
